export const BUILDER_TILE_SIZE = 14;

export const WORLD_HALF_EXTENT = BUILDER_TILE_SIZE * 12;
export const WORLD_GRID_SIZE = WORLD_HALF_EXTENT * 2;
export const WORLD_GRID_DIVISIONS = WORLD_GRID_SIZE / BUILDER_TILE_SIZE;
export const WORLD_GROUND_RADIUS = WORLD_HALF_EXTENT + BUILDER_TILE_SIZE * 2;
export const WORLD_SHADOW_EXTENT = WORLD_HALF_EXTENT + BUILDER_TILE_SIZE * 2;
export const WORLD_FOG_NEAR = WORLD_HALF_EXTENT * 0.8;
export const WORLD_FOG_FAR = WORLD_GROUND_RADIUS + BUILDER_TILE_SIZE * 2;
