create table if not exists public.agent_json_state (
  state_key text primary key,
  payload jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.world_snapshots (
  world_key text primary key,
  layout jsonb not null,
  updated_at timestamptz not null default now(),
  version bigint not null default 1
);

create table if not exists public.world_snapshot_backups (
  id bigint generated by default as identity primary key,
  world_key text not null,
  layout jsonb not null,
  layout_hash text not null,
  source_version bigint,
  captured_at timestamptz not null default now(),
  backup_kind text not null default 'periodic'
);

create index if not exists world_snapshot_backups_world_key_captured_at_idx
  on public.world_snapshot_backups (world_key, captured_at desc);

create table if not exists public.stock_market_snapshots (
  world_key text primary key,
  snapshot jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.player_snapshots (
  world_key text not null,
  player_id text not null,
  snapshot jsonb not null,
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null,
  primary key (world_key, player_id)
);

create index if not exists player_snapshots_expires_at_idx
  on public.player_snapshots (expires_at);
